# Generated by Django 3.2.9 on 2021-11-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='station name')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_railcar', models.IntegerField(verbose_name='number of railcar')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.station', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price_from_start', models.PositiveIntegerField(verbose_name='price')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.route', verbose_name='')),
                ('stations', models.ManyToManyField(to='search_ticket.Station', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='search_ticket.station', verbose_name='End name'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='search_ticket.station', verbose_name='Start name'),
        ),
        migrations.AddField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.train', verbose_name='train'),
        ),
    ]
