# Generated by Django 3.2.9 on 2021-11-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='station',
        ),
        migrations.CreateModel(
            name='RoutTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routtrain_route', to='search_ticket.route', verbose_name='')),
                ('train', models.ManyToManyField(related_name='routtrain_train', to='search_ticket.Train', verbose_name='')),
            ],
        ),
    ]
