# Generated by Django 3.2.9 on 2021-11-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0002_auto_20211123_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.route'),
        ),
        migrations.AlterField(
            model_name='routtrain',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routtrain_route', to='search_ticket.route'),
        ),
    ]
