# Generated by Django 3.2.9 on 2021-11-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0003_auto_20211123_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rout_train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rout_train', to='search_ticket.routtrain'),
        ),
    ]
