# Generated by Django 3.2.9 on 2021-11-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0005_remove_route_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rout_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rout_train', to='search_ticket.routtrain'),
        ),
        migrations.AlterField(
            model_name='route',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
