# Generated by Django 3.2.9 on 2021-12-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0007_route_rout_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestation',
            name='route',
        ),
    ]
