# Generated by Django 3.2.9 on 2021-12-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0008_remove_routestation_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='rout_station',
        ),
        migrations.AddField(
            model_name='routestation',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_ticket.route'),
        ),
    ]
