# Generated by Django 3.2.9 on 2021-12-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0009_auto_20211212_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='rout_train',
        ),
    ]
