# Generated by Django 3.2.9 on 2021-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0010_remove_route_rout_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
