# Generated by Django 3.2.9 on 2021-11-14 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2}[0-9]{8}')])),
                ('discount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RailCarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='railcar_type_name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railcar_number', models.PositiveIntegerField(verbose_name='')),
                ('seat', models.PositiveIntegerField(verbose_name='')),
                ('purchase_date', models.DateField(verbose_name='')),
                ('departure_date', models.DateTimeField(verbose_name='')),
                ('is_taken', models.BooleanField(default=False, verbose_name='')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.route', verbose_name='')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.train', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Railcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('amount_of_seats', models.PositiveBigIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.train', verbose_name='')),
                ('type_of_railcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.railcartype', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='name')),
                ('customer_surname', models.CharField(max_length=50, verbose_name='surname')),
                ('customer_patronymic', models.CharField(max_length=50, verbose_name='patronymic')),
                ('price', models.PositiveIntegerField(verbose_name='ticket price')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[\\w.]+@[\\w-]+.+[\\w-]{2,4}$')], verbose_name='customer email')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.discount', verbose_name='')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_end', to='search_ticket.station', verbose_name='End name')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_start', to='search_ticket.station', verbose_name='Start name')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.ticket', verbose_name='')),
            ],
        ),
    ]
