# Generated by Django 3.2.9 on 2021-11-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_ticket', '0003_auto_20211123_1914'),
        ('order_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.discount'),
        ),
        migrations.AlterField(
            model_name='orderticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.ticket'),
        ),
        migrations.AlterField(
            model_name='railcar',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.train'),
        ),
        migrations.AlterField(
            model_name='railcar',
            name='type_of_railcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_ticket.railcartype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.route'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_ticket.train'),
        ),
    ]
