# Generated by Django 3.2.9 on 2021-11-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_ticket', '0003_alter_railcar_amount_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='railcar_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.PositiveIntegerField(),
        ),
    ]
