# Generated by Django 3.2.9 on 2021-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_ticket', '0004_auto_20211123_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
