# Generated by Django 3.2.9 on 2021-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_ticket', '0005_auto_20211212_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderticket',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
