# Generated by Django 3.2.9 on 2021-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_ticket', '0006_orderticket_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
