# Generated by Django 3.2.9 on 2021-12-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_ticket', '0007_alter_orderticket_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderticket',
            name='customer_patronymic',
        ),
    ]
